### ISSUE TITLE
Using InnerHTML instead of innerText

### ISSUE THREAD

**Issue by miggs125** [lozinska/my-note#4]
Hi,

In the index.html file, I noticed that you are using innerHTML instead of InnerText when accessing the input from the note. I think it would be better to use innerText instead because of the [difference between innerHTML and innerText](https://stackoverflow.com/questions/19030742/difference-between-innertext-and-innerhtml).

Do you mind if I create a PR for this?

**Comment by lozinska** [comment]
Go for it
